package id.sekawan.point.util

const val CONFIG_BIND_PORT = "bind_port"
const val CONFIG_WEB_WAIT_SHUTDOWN_MS = "web.wait_before_shutdown_ms"

const val CONFIG_SATU_DB_URL = "satu_db_url"
const val CONFIG_SATU_DB_MIN_POOL = "satu_db_min_pool"
const val CONFIG_SATU_DB_MAX_POOL = "satu_db_max_pool"
const val CONFIG_SATU_DB_USER = "satu_db_user"
const val CONFIG_SATU_DB_PASS = "satu_db_pass"
const val CONFIG_SATU_DB_PORT = "satu_db_port"
const val CONFIG_SATU_DB_NAME = "satu_db_name"
const val CONFIG_SATU_DB_HOST = "satu_db_host"
const val CONFIG_SATU_DB_CONNECT_TIMEOUT_MS = "satu_db_connect_timeout_ms"
const val CONFIG_SATU_DB_IDLE_TIMEOUT_MS = "satu_db_idle_timeout_ms"
const val CONFIG_SATU_DB_LEAK_DETECTION_IN_MS = "satu_db_leak_detection_in_ms"
const val CONFIG_SECRET_JWT = "secret.jwt"
const val CONFIG_IS_ACTIVE_FREEMAKER_CACHE = "is_active_freemaker_cache"
const val CONFIG_IS_ACTIVE_WEB_LOCAL_CACHE = "is_active_web_local_cache"
const val CONFIG_HASH_SALT = "hash_salt"
const val CONFIG_TEST_MAX_LOP= "test.max.loop"
